# Spring property source for the Tingo application, providing development configuration
# Note that properties are considered in this order:
# http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config
# This is used by default, however ignored if the dev profile is not enabled.

# Enable more verbose logging on core loggers
#debug: true
