# Spring property source for the sic application, providing default configuration
# Note that properties are considered in this order:
# http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config


spring:
  profiles:
    active:
     - dev

  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 1
      maximum-pool-size: 10
  flyway:
    # migrate if we don't have a baseline defined, i.e. Flyway has never run on that database.
    #baseline-on-migrate: true
    encoding: UTF-8
    #baseline-version: 0

logging:
    level:
      org:
        springframework:
          boot:
            actuate:
              metrics:
                # Log Statsd errors
                statsd: DEBUG

sic:
  # Secret code needed to register a new account
  registerSecret: my-secret
  # Additional HTML to add to the footer
  footerText: 'This service is provided by Aperture Laboratories. Change this text in application.yml.'
  # Whether to enable random pranks and trolls on the users
  enablePranks: false
  # The YouTube id of the 'introductory' video
  videoUrl: 'cRpdIrq7Rbo'
  # access code for guest (readonly) access
  guestCode: ''
  # additional navbar links
  #navbarLinks:
  #  - caption: Link text
  #    url:     target URL
  statsdEnabled: false

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
  server:
    port: 8081
