apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sic.fullname" . }}
  labels:
    {{- include "sic.labels" . | nindent 4 }}
data:
  application.yml: >-
    spring:
      profiles:
        active: []
    sic:
      footerText: 'was stand hier ich kann es nicht mehr sagen'
      enablePranks: true
      videoUrl: 'cRpdIrq7Rbo'
      navbarLinks:
        - caption: 'Neue Zitate'
          url: 'state://newquotes'
        - caption: 'Beste Zitate'
          url: 'state://bestquotes'
        - caption: 'Source'
          url: 'https://github.com/literalplus/sic'
        - caption: 'Tingo'
          url: 'https://tingo.lit.plus'
      statsdEnabled: false
